-- =========================================================
-- Cleanup Legacy Database Tables Script
-- Drops all 63 old tables, retaining ONLY the 12 updated tables created today
-- =========================================================

DROP TABLE IF EXISTS
  edu_jobrole_modules,
  django_content_type,
  edu_mcqquestion,
  auth_permission,
  edu_user_activity_summary,
  edu_yoyquestion,
  django_admin_log,
  edu_savedjob,
  edu_user_user_permissions,
  edu_interviewquestion,
  edu_video_progress,
  edu_miniproject,
  edu_dau,
  edu_mcqattempt,
  auth_group,
  edu_yoysession,
  edu_user,
  token_blacklist_blacklistedtoken,
  edu_course_progress,
  edu_company,
  django_session,
  edu_course,
  edu_interviewmcqquestion,
  edu_module,
  edu_studymaterial,
  edu_domain,
  edu_jobsynclog,
  edu_jobopening,
  edu_interviewsession,
  edu_lesson_analytics_summary,
  edu_lesson,
  edu_audit_log,
  edu_assessmentattempt,
  edu_lesson_progress,
  edu_short_note,
  edu_course_rating,
  edu_emailverificationtoken,
  edu_tag,
  edu_careermcqquestion,
  edu_sectionattempt,
  edu_discussioncomment,
  edu_engineeringbranch,
  edu_jobrole,
  edu_video_progress_event,
  edu_user_groups,
  edu_programmingquestion,
  edu_short_note_purchase,
  token_blacklist_outstandingtoken,
  edu_yoyassessment,
  edu_assessmentsection,
  edu_course_analytics_summary,
  edu_analytics_event,
  edu_assessment,
  edu_course_tags,
  edu_yoyquestionattempt,
  edu_doityourselfquestion,
  edu_passwordresettoken,
  auth_group_permissions,
  edu_interviewquestionattempt,
  edu_communitypost,
  edu_interviewanswer,
  edu_interviewquestion_is_bookmarked_by,
  edu_enrollment
CASCADE;

-- Verification Query: List remaining active tables in public schema
SELECT table_name 
FROM information_schema.tables 
WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
ORDER BY table_name;
