-- Cranes Digital Academy — COMPLETE database schema (structure only, no data)
-- Run this in the Supabase SQL Editor to recreate the full schema.
-- Generated Fri Jul 24 20:09:49 IST 2026

-- ===== contenttypes.0001_initial =====
BEGIN;
--
-- Create model ContentType
--
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
--
-- Alter unique_together for contenttype (1 constraint(s))
--
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");
COMMIT;

-- ===== contenttypes.0002_remove_content_type_name =====
BEGIN;
--
-- Change Meta options on contenttype
--
-- (no-op)
--
-- Alter field name on contenttype
--
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field name from contenttype
--
ALTER TABLE "django_content_type" DROP COLUMN "name";
COMMIT;

-- ===== auth.0001_initial =====
BEGIN;
--
-- Create model Permission
--
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
--
-- Create model Group
--
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model User
--
-- (no-op)
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
COMMIT;

-- ===== auth.0002_alter_permission_name_max_length =====
BEGIN;
--
-- Alter field name on permission
--
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255);
COMMIT;

-- ===== auth.0003_alter_user_email_max_length =====
BEGIN;
--
-- Alter field email on user
--
-- (no-op)
COMMIT;

-- ===== auth.0004_alter_user_username_opts =====
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- ===== auth.0005_alter_user_last_login_null =====
BEGIN;
--
-- Alter field last_login on user
--
-- (no-op)
COMMIT;

-- ===== auth.0006_require_contenttypes_0002 =====

-- ===== auth.0007_alter_validators_add_error_messages =====
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- ===== auth.0008_alter_user_username_max_length =====
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- ===== auth.0009_alter_user_last_name_max_length =====
BEGIN;
--
-- Alter field last_name on user
--
-- (no-op)
COMMIT;

-- ===== auth.0010_alter_group_name_max_length =====
BEGIN;
--
-- Alter field name on group
--
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150);
COMMIT;

-- ===== auth.0011_update_proxy_permissions =====
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- ===== auth.0012_alter_user_first_name_max_length =====
BEGIN;
--
-- Alter field first_name on user
--
-- (no-op)
COMMIT;

-- ===== edu.0001_initial =====
BEGIN;
--
-- Create model DoItYourselfQuestion
--
CREATE TABLE "edu_doityourselfquestion" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "course" varchar(150) NOT NULL, "track" varchar(255) NOT NULL, "topic" varchar(150) NOT NULL, "hardware" varchar(255) NULL, "concept" varchar(255) NOT NULL, "difficulty" varchar(20) NOT NULL, "title" varchar(255) NOT NULL, "abstract" text NOT NULL, "problem_statement" text NOT NULL, "constraints" text NOT NULL, "expected_output" text NOT NULL, "sample_io" jsonb NOT NULL, "is_published" boolean NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0), "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
--
-- Create model InterviewMCQQuestion
--
CREATE TABLE "edu_interviewmcqquestion" ("id" uuid NOT NULL PRIMARY KEY, "question" text NOT NULL, "question_image" varchar(2048) NOT NULL, "option_a" varchar(500) NOT NULL, "option_b" varchar(500) NOT NULL, "option_c" varchar(500) NOT NULL, "option_d" varchar(500) NOT NULL, "correct_option" varchar(1) NOT NULL, "explanation" text NOT NULL, "difficulty" varchar(20) NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0), "created_at" timestamp with time zone NOT NULL);
--
-- Create model JobRole
--
CREATE TABLE "edu_jobrole" ("id" uuid NOT NULL PRIMARY KEY, "title" varchar(255) NOT NULL, "description" text NOT NULL, "icon" varchar(10) NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0), "is_published" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL);
--
-- Create model Lesson
--
CREATE TABLE "edu_lesson" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "title" varchar(2550) NOT NULL, "lesson_type" varchar(20) NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0), "description" text NOT NULL, "is_preview" boolean NOT NULL, "video_url" varchar(2048) NOT NULL, "video_duration_seconds" integer NULL CHECK ("video_duration_seconds" >= 0), "document_url" varchar(200) NOT NULL, "external_url" varchar(200) NOT NULL, "text_content" text NOT NULL, "estimated_duration_minutes" integer NULL CHECK ("estimated_duration_minutes" >= 0), "view_count" integer NOT NULL CHECK ("view_count" >= 0), "completion_count" integer NOT NULL CHECK ("completion_count" >= 0));
--
-- Create model MCQQuestion
--
CREATE TABLE "edu_mcqquestion" ("id" uuid NOT NULL PRIMARY KEY, "mcq_test_no" integer NOT NULL CHECK ("mcq_test_no" >= 0), "question" text NOT NULL, "question_image_url" varchar(2048) NOT NULL, "option_a" varchar(500) NOT NULL, "option_b" varchar(500) NOT NULL, "option_c" varchar(500) NOT NULL, "option_d" varchar(500) NOT NULL, "correct_option" varchar(1) NOT NULL, "explanation" text NOT NULL, "created_at" timestamp with time zone NOT NULL);
--
-- Create model Tag
--
CREATE TABLE "edu_tag" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL UNIQUE, "slug" varchar(50) NOT NULL UNIQUE);
--
-- Create model User
--
CREATE TABLE "edu_user" ("password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "email" varchar(254) NOT NULL UNIQUE, "role" varchar(20) NOT NULL, "avatar_url" varchar(200) NOT NULL, "bio" text NOT NULL, "timezone" varchar(50) NOT NULL, "preferred_lang" varchar(10) NOT NULL, "phone_number" varchar(20) NULL, "is_email_verified" boolean NOT NULL, "degree" varchar(255) NULL, "branch" varchar(255) NULL, "college" varchar(555) NULL, "roll" varchar(20) NULL, "last_seen_at" timestamp with time zone NULL, "courses_enrolled" integer NOT NULL CHECK ("courses_enrolled" >= 0), "courses_completed" integer NOT NULL CHECK ("courses_completed" >= 0), "current_streak" integer NOT NULL CHECK ("current_streak" >= 0), "longest_streak" integer NOT NULL CHECK ("longest_streak" >= 0), "last_streak_date" date NULL, "total_active_seconds" integer NOT NULL CHECK ("total_active_seconds" >= 0));
CREATE TABLE "edu_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" uuid NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "edu_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" uuid NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model AuditLog
--
CREATE TABLE "edu_audit_log" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(20) NOT NULL, "resource_type" varchar(50) NOT NULL, "resource_id" varchar(64) NOT NULL, "changes" jsonb NOT NULL, "ip_address" inet NULL, "user_agent" text NOT NULL, "extra" jsonb NOT NULL, "created_at" timestamp with time zone NOT NULL, "actor_id" uuid NULL);
--
-- Create model CommunityPost
--
CREATE TABLE "edu_communitypost" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "content" text NOT NULL, "media" varchar(100) NULL, "media_type" varchar(10) NULL, "created_at" timestamp with time zone NOT NULL, "author_id" uuid NOT NULL);
--
-- Create model Course
--
CREATE TABLE "edu_course" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "title" varchar(255) NOT NULL, "slug" varchar(255) NOT NULL UNIQUE, "description" text NOT NULL, "short_description" varchar(500) NOT NULL, "thumbnail_url" varchar(200) NOT NULL, "language" varchar(10) NOT NULL, "difficulty" varchar(20) NOT NULL, "price" numeric(10, 2) NOT NULL, "is_free" boolean NOT NULL, "target_audience" varchar(255) NULL, "learning_mode" varchar(255) NULL, "prerequisites" text NOT NULL, "why_this_course" text NOT NULL, "learning_outcomes" text NOT NULL, "certification_info" text NOT NULL, "industry_demand" text NOT NULL, "career_opportunities" text NOT NULL, "Industry_relevance" text NOT NULL, "short_note" text NOT NULL, "curriculum" jsonb NOT NULL, "career_paths" jsonb NOT NULL, "status" varchar(20) NOT NULL, "published_at" timestamp with time zone NULL, "total_lessons" integer NOT NULL CHECK ("total_lessons" >= 0), "estimated_duration_minutes" integer NULL CHECK ("estimated_duration_minutes" >= 0), "enrolled_count" integer NOT NULL CHECK ("enrolled_count" >= 0), "completion_count" integer NOT NULL CHECK ("completion_count" >= 0), "instructor_id" uuid NULL);
CREATE TABLE "edu_course_tags" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "course_id" uuid NOT NULL, "tag_id" bigint NOT NULL);
--
-- Create model CourseAnalyticsSummary
--
CREATE TABLE "edu_course_analytics_summary" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL, "new_enrollments" integer NOT NULL CHECK ("new_enrollments" >= 0), "total_enrollments" integer NOT NULL CHECK ("total_enrollments" >= 0), "active_learners" integer NOT NULL CHECK ("active_learners" >= 0), "drops" integer NOT NULL CHECK ("drops" >= 0), "completions" integer NOT NULL CHECK ("completions" >= 0), "total_completions" integer NOT NULL CHECK ("total_completions" >= 0), "total_lesson_views" integer NOT NULL CHECK ("total_lesson_views" >= 0), "unique_lesson_views" integer NOT NULL CHECK ("unique_lesson_views" >= 0), "avg_progress_pct" numeric(5, 2) NOT NULL, "total_time_spent_seconds" bigint NOT NULL CHECK ("total_time_spent_seconds" >= 0), "revenue" numeric(12, 2) NOT NULL, "course_id" uuid NOT NULL);
--
-- Create model CourseRating
--
CREATE TABLE "edu_course_rating" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "rating" smallint NOT NULL CHECK ("rating" >= 0), "review" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "course_id" uuid NOT NULL, "user_id" uuid NOT NULL);
--
-- Create model DailyActiveUser
--
CREATE TABLE "edu_dau" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL, "event_count" integer NOT NULL CHECK ("event_count" >= 0), "lessons_accessed" integer NOT NULL CHECK ("lessons_accessed" >= 0), "time_spent_seconds" integer NOT NULL CHECK ("time_spent_seconds" >= 0), "user_id" uuid NOT NULL);
--
-- Create model EmailVerificationToken
--
CREATE TABLE "edu_emailverificationtoken" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "token" uuid NOT NULL UNIQUE, "created_at" timestamp with time zone NOT NULL, "user_id" uuid NOT NULL UNIQUE);
--
-- Create model Enrollment
--
CREATE TABLE "edu_enrollment" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "status" varchar(20) NOT NULL, "payment_status" varchar(20) NOT NULL, "payment_reference" varchar(255) NOT NULL, "amount_paid" numeric(10, 2) NOT NULL, "enrolled_at" timestamp with time zone NOT NULL, "last_accessed_at" timestamp with time zone NULL, "completed_at" timestamp with time zone NULL, "dropped_at" timestamp with time zone NULL, "suspended_at" timestamp with time zone NULL, "progress_pct" numeric(5, 2) NOT NULL, "total_time_spent_seconds" integer NOT NULL CHECK ("total_time_spent_seconds" >= 0), "course_id" uuid NOT NULL, "user_id" uuid NOT NULL);
--
-- Create model InterviewQuestion
--
CREATE TABLE "edu_interviewquestion" ("id" uuid NOT NULL PRIMARY KEY, "excel_id" integer NULL UNIQUE CHECK ("excel_id" >= 0), "title" varchar(500) NOT NULL, "body" text NOT NULL, "tags" jsonb NOT NULL, "difficulty" varchar(10) NOT NULL, "created_at" timestamp with time zone NOT NULL, "course_id" uuid NOT NULL);
CREATE TABLE "edu_interviewquestion_is_bookmarked_by" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "interviewquestion_id" uuid NOT NULL, "user_id" uuid NOT NULL);
--
-- Create model InterviewAnswer
--
CREATE TABLE "edu_interviewanswer" ("id" uuid NOT NULL PRIMARY KEY, "body" text NOT NULL, "order" smallint NOT NULL CHECK ("order" >= 0), "question_id" uuid NOT NULL);
--
-- Create model InterviewSession
--
CREATE TABLE "edu_interviewsession" ("id" uuid NOT NULL PRIMARY KEY, "status" varchar(20) NOT NULL, "score" integer NOT NULL CHECK ("score" >= 0), "total" integer NOT NULL CHECK ("total" >= 0), "attempt_no" integer NOT NULL CHECK ("attempt_no" >= 0), "started_at" timestamp with time zone NOT NULL, "completed_at" timestamp with time zone NULL, "user_id" uuid NOT NULL, "job_role_id" uuid NOT NULL);
--
-- Create model InterviewQuestionAttempt
--
CREATE TABLE "edu_interviewquestionattempt" ("id" uuid NOT NULL PRIMARY KEY, "selected_option" varchar(1) NOT NULL, "is_correct" boolean NOT NULL, "answered_at" timestamp with time zone NOT NULL, "question_id" uuid NOT NULL, "session_id" uuid NOT NULL);
--
-- Create model DiscussionComment
--
CREATE TABLE "edu_discussioncomment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "body" text NOT NULL, "is_edited" boolean NOT NULL, "is_deleted" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "author_id" uuid NOT NULL, "reply_to_id" bigint NULL, "lesson_id" uuid NOT NULL);
--
-- Create model CourseProgress
--
CREATE TABLE "edu_course_progress" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "lessons_completed" integer NOT NULL CHECK ("lessons_completed" >= 0), "total_lessons" integer NOT NULL CHECK ("total_lessons" >= 0), "progress_pct" numeric(5, 2) NOT NULL, "total_time_spent_seconds" integer NOT NULL CHECK ("total_time_spent_seconds" >= 0), "last_accessed_at" timestamp with time zone NULL, "is_completed" boolean NOT NULL, "completed_at" timestamp with time zone NULL, "course_id" uuid NOT NULL, "user_id" uuid NOT NULL, "last_accessed_lesson_id" uuid NULL);
--
-- Create model AnalyticsEvent
--
CREATE TABLE "edu_analytics_event" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "event_type" varchar(50) NOT NULL, "metadata" jsonb NOT NULL, "session_id" varchar(64) NOT NULL, "ip_address" inet NULL, "user_agent" text NOT NULL, "referrer" varchar(200) NOT NULL, "platform" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL, "user_id" uuid NULL, "course_id" uuid NULL, "lesson_id" uuid NULL);
--
-- Create model LessonAnalyticsSummary
--
CREATE TABLE "edu_lesson_analytics_summary" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL, "views" integer NOT NULL CHECK ("views" >= 0), "unique_views" integer NOT NULL CHECK ("unique_views" >= 0), "completions" integer NOT NULL CHECK ("completions" >= 0), "completion_rate" numeric(5, 2) NOT NULL, "avg_watch_pct" numeric(5, 2) NOT NULL, "avg_time_spent_seconds" integer NOT NULL CHECK ("avg_time_spent_seconds" >= 0), "drop_off_position_seconds" integer NULL CHECK ("drop_off_position_seconds" >= 0), "lesson_id" uuid NOT NULL);
--
-- Create model LessonProgress
--
CREATE TABLE "edu_lesson_progress" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "is_completed" boolean NOT NULL, "completed_at" timestamp with time zone NULL, "last_accessed_at" timestamp with time zone NULL, "access_count" integer NOT NULL CHECK ("access_count" >= 0), "lesson_id" uuid NOT NULL, "user_id" uuid NOT NULL);
--
-- Create model MCQAttempt
--
CREATE TABLE "edu_mcqattempt" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "selected_option" varchar(1) NOT NULL, "is_correct" boolean NOT NULL, "attempted_at" timestamp with time zone NOT NULL, "user_id" uuid NOT NULL, "question_id" uuid NOT NULL);
--
-- Create model MiniProject
--
CREATE TABLE "edu_miniproject" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(255) NOT NULL, "difficulty" varchar(20) NOT NULL, "topic" varchar(150) NOT NULL, "concept" varchar(255) NOT NULL, "track" varchar(255) NOT NULL, "abstract" text NOT NULL, "problem_statement" text NOT NULL, "objectives" text NOT NULL, "constraints" text NOT NULL, "expected_output" text NOT NULL, "sample_io" jsonb NOT NULL, "deliverables" text NOT NULL, "hints" text NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0), "is_published" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "course_id" uuid NOT NULL);
--
-- Create model Module
--
CREATE TABLE "edu_module" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "deleted_at" timestamp with time zone NULL, "id" uuid NOT NULL PRIMARY KEY, "title" varchar(255) NOT NULL, "description" text NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0), "course_id" uuid NOT NULL);
--
-- Add field module to mcqquestion
--
ALTER TABLE "edu_mcqquestion" ADD COLUMN "module_id" uuid NOT NULL CONSTRAINT "edu_mcqquestion_module_id_f47b2436_fk_edu_module_id" REFERENCES "edu_module"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "edu_mcqquestion_module_id_f47b2436_fk_edu_module_id" IMMEDIATE;
--
-- Add field module to lesson
--
ALTER TABLE "edu_lesson" ADD COLUMN "module_id" uuid NOT NULL CONSTRAINT "edu_lesson_module_id_22be4787_fk_edu_module_id" REFERENCES "edu_module"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "edu_lesson_module_id_22be4787_fk_edu_module_id" IMMEDIATE;
--
-- Add field modules to jobrole
--
CREATE TABLE "edu_jobrole_modules" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "jobrole_id" uuid NOT NULL, "module_id" uuid NOT NULL);
--
-- Add field module to interviewsession
--
ALTER TABLE "edu_interviewsession" ADD COLUMN "module_id" uuid NOT NULL CONSTRAINT "edu_interviewsession_module_id_1994c7b1_fk_edu_module_id" REFERENCES "edu_module"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "edu_interviewsession_module_id_1994c7b1_fk_edu_module_id" IMMEDIATE;
--
-- Add field module to interviewmcqquestion
--
ALTER TABLE "edu_interviewmcqquestion" ADD COLUMN "module_id" uuid NOT NULL CONSTRAINT "edu_interviewmcqquestion_module_id_73f19670_fk_edu_module_id" REFERENCES "edu_module"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "edu_interviewmcqquestion_module_id_73f19670_fk_edu_module_id" IMMEDIATE;
--
-- Create model PasswordResetToken
--
CREATE TABLE "edu_passwordresettoken" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "token" uuid NOT NULL UNIQUE, "created_at" timestamp with time zone NOT NULL, "user_id" uuid NOT NULL UNIQUE);
--
-- Create model ProgrammingQuestion
--
CREATE TABLE "edu_programmingquestion" ("id" uuid NOT NULL PRIMARY KEY, "title" varchar(500) NOT NULL, "problem_statement" text NOT NULL, "constraints" text NOT NULL, "example_input" text NOT NULL, "example_output" text NOT NULL, "hint" text NOT NULL, "difficulty" varchar(10) NOT NULL, "tags" jsonb NOT NULL, "created_at" timestamp with time zone NOT NULL, "course_id" uuid NOT NULL);
--
-- Create model StudyMaterial
--
CREATE TABLE "edu_studymaterial" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(255) NOT NULL, "description" text NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0), "material_type" varchar(10) NOT NULL, "file" varchar(100) NULL, "file_type" varchar(10) NOT NULL, "external_link" varchar(200) NOT NULL, "is_published" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "course_id" uuid NOT NULL);
--
-- Create model UserActivitySummary
--
CREATE TABLE "edu_user_activity_summary" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "date" date NOT NULL, "events_count" integer NOT NULL CHECK ("events_count" >= 0), "lessons_viewed" integer NOT NULL CHECK ("lessons_viewed" >= 0), "lessons_completed" integer NOT NULL CHECK ("lessons_completed" >= 0), "courses_accessed" integer NOT NULL CHECK ("courses_accessed" >= 0), "time_spent_seconds" integer NOT NULL CHECK ("time_spent_seconds" >= 0), "user_id" uuid NOT NULL);
--
-- Create model VideoProgress
--
CREATE TABLE "edu_video_progress" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "last_position_seconds" integer NOT NULL CHECK ("last_position_seconds" >= 0), "max_reached_seconds" integer NOT NULL CHECK ("max_reached_seconds" >= 0), "watch_percentage" numeric(5, 2) NOT NULL, "total_watch_time_seconds" integer NOT NULL CHECK ("total_watch_time_seconds" >= 0), "play_count" integer NOT NULL CHECK ("play_count" >= 0), "last_watched_at" timestamp with time zone NULL, "lesson_id" uuid NOT NULL, "user_id" uuid NOT NULL);
--
-- Create model VideoProgressEvent
--
CREATE TABLE "edu_video_progress_event" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "event_type" varchar(20) NOT NULL, "position_seconds" integer NOT NULL CHECK ("position_seconds" >= 0), "playback_speed" numeric(3, 1) NOT NULL, "session_id" varchar(64) NOT NULL, "created_at" timestamp with time zone NOT NULL, "lesson_id" uuid NOT NULL, "user_id" uuid NOT NULL);
--
-- Create model YoYAssessment
--
CREATE TABLE "edu_yoyassessment" ("id" uuid NOT NULL PRIMARY KEY, "title" varchar(255) NOT NULL, "description" text NOT NULL, "scope" varchar(255) NOT NULL, "academic_year" varchar(20) NOT NULL, "scheduled_start" timestamp with time zone NOT NULL, "scheduled_end" timestamp with time zone NOT NULL, "is_published" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "module_id" uuid NULL);
--
-- Create model YoYQuestion
--
CREATE TABLE "edu_yoyquestion" ("id" uuid NOT NULL PRIMARY KEY, "question" text NOT NULL, "option_a" varchar(500) NOT NULL, "option_b" varchar(500) NOT NULL, "option_c" varchar(500) NOT NULL, "option_d" varchar(500) NOT NULL, "correct_option" varchar(1) NOT NULL, "explanation" text NOT NULL, "order" integer NOT NULL CHECK ("order" >= 0), "assessment_id" uuid NOT NULL);
--
-- Create model YoYSession
--
CREATE TABLE "edu_yoysession" ("id" uuid NOT NULL PRIMARY KEY, "status" varchar(20) NOT NULL, "score" integer NOT NULL CHECK ("score" >= 0), "total" integer NOT NULL CHECK ("total" >= 0), "attempt_no" integer NOT NULL CHECK ("attempt_no" >= 0), "started_at" timestamp with time zone NOT NULL, "completed_at" timestamp with time zone NULL, "assessment_id" uuid NOT NULL, "user_id" uuid NOT NULL);
--
-- Create model YoYQuestionAttempt
--
CREATE TABLE "edu_yoyquestionattempt" ("id" uuid NOT NULL PRIMARY KEY, "selected_option" varchar(1) NOT NULL, "is_correct" boolean NOT NULL, "answered_at" timestamp with time zone NOT NULL, "question_id" uuid NOT NULL, "session_id" uuid NOT NULL);
--
-- Create index edu_user_role_fa8093_idx on field(s) role, is_active of model user
--
CREATE INDEX "edu_user_role_fa8093_idx" ON "edu_user" ("role", "is_active");
--
-- Create index edu_user_role_1bb268_idx on field(s) role, created_at of model user
--
CREATE INDEX "edu_user_role_1bb268_idx" ON "edu_user" ("role", "created_at");
--
-- Create index edu_user_last_se_1e7a57_idx on field(s) last_seen_at of model user
--
CREATE INDEX "edu_user_last_se_1e7a57_idx" ON "edu_user" ("last_seen_at");
--
-- Create index edu_user_is_emai_0649f8_idx on field(s) is_email_verified, is_active of model user
--
CREATE INDEX "edu_user_is_emai_0649f8_idx" ON "edu_user" ("is_email_verified", "is_active");
--
-- Create index edu_audit_l_actor_i_1f66a5_idx on field(s) actor, created_at of model auditlog
--
CREATE INDEX "edu_audit_l_actor_i_1f66a5_idx" ON "edu_audit_log" ("actor_id", "created_at");
--
-- Create index edu_audit_l_resourc_966c34_idx on field(s) resource_type, resource_id of model auditlog
--
CREATE INDEX "edu_audit_l_resourc_966c34_idx" ON "edu_audit_log" ("resource_type", "resource_id");
--
-- Create index edu_audit_l_resourc_1395c5_idx on field(s) resource_type, action, created_at of model auditlog
--
CREATE INDEX "edu_audit_l_resourc_1395c5_idx" ON "edu_audit_log" ("resource_type", "action", "created_at");
--
-- Create index edu_audit_l_action_58eee5_idx on field(s) action, created_at of model auditlog
--
CREATE INDEX "edu_audit_l_action_58eee5_idx" ON "edu_audit_log" ("action", "created_at");
--
-- Create index edu_audit_l_created_bfba8f_idx on field(s) created_at of model auditlog
--
CREATE INDEX "edu_audit_l_created_bfba8f_idx" ON "edu_audit_log" ("created_at");
--
-- Create index edu_course__course__736033_idx on field(s) course, date of model courseanalyticssummary
--
CREATE INDEX "edu_course__course__736033_idx" ON "edu_course_analytics_summary" ("course_id", "date");
--
-- Create index edu_course__date_9e43cc_idx on field(s) date of model courseanalyticssummary
--
CREATE INDEX "edu_course__date_9e43cc_idx" ON "edu_course_analytics_summary" ("date");
--
-- Alter unique_together for courseanalyticssummary (1 constraint(s))
--
ALTER TABLE "edu_course_analytics_summary" ADD CONSTRAINT "edu_course_analytics_summary_course_id_date_874dd19a_uniq" UNIQUE ("course_id", "date");
--
-- Create index edu_course__course__37d185_idx on field(s) course, rating of model courserating
--
CREATE INDEX "edu_course__course__37d185_idx" ON "edu_course_rating" ("course_id", "rating");
--
-- Create index edu_course__course__a65856_idx on field(s) course, created_at of model courserating
--
CREATE INDEX "edu_course__course__a65856_idx" ON "edu_course_rating" ("course_id", "created_at");
--
-- Alter unique_together for courserating (1 constraint(s))
--
ALTER TABLE "edu_course_rating" ADD CONSTRAINT "edu_course_rating_user_id_course_id_7825bb27_uniq" UNIQUE ("user_id", "course_id");
--
-- Create index edu_dau_date_3671e0_idx on field(s) date of model dailyactiveuser
--
CREATE INDEX "edu_dau_date_3671e0_idx" ON "edu_dau" ("date");
--
-- Create index edu_dau_user_id_42aca1_idx on field(s) user, date of model dailyactiveuser
--
CREATE INDEX "edu_dau_user_id_42aca1_idx" ON "edu_dau" ("user_id", "date");
--
-- Alter unique_together for dailyactiveuser (1 constraint(s))
--
ALTER TABLE "edu_dau" ADD CONSTRAINT "edu_dau_user_id_date_61a98bee_uniq" UNIQUE ("user_id", "date");
--
-- Create index edu_enrollm_user_id_260188_idx on field(s) user, status of model enrollment
--
CREATE INDEX "edu_enrollm_user_id_260188_idx" ON "edu_enrollment" ("user_id", "status");
--
-- Create index edu_enrollm_course__e04214_idx on field(s) course, status of model enrollment
--
CREATE INDEX "edu_enrollm_course__e04214_idx" ON "edu_enrollment" ("course_id", "status");
--
-- Create index edu_enrollm_course__0b200b_idx on field(s) course, payment_status of model enrollment
--
CREATE INDEX "edu_enrollm_course__0b200b_idx" ON "edu_enrollment" ("course_id", "payment_status");
--
-- Create index edu_enrollm_enrolle_1be3cb_idx on field(s) enrolled_at, status of model enrollment
--
CREATE INDEX "edu_enrollm_enrolle_1be3cb_idx" ON "edu_enrollment" ("enrolled_at", "status");
--
-- Create index edu_enrollm_complet_6ab51f_idx on field(s) completed_at of model enrollment
--
CREATE INDEX "edu_enrollm_complet_6ab51f_idx" ON "edu_enrollment" ("completed_at");
--
-- Create index edu_enrollm_course__8c215e_idx on field(s) course, enrolled_at of model enrollment
--
CREATE INDEX "edu_enrollm_course__8c215e_idx" ON "edu_enrollment" ("course_id", "enrolled_at");
--
-- Alter unique_together for enrollment (1 constraint(s))
--
ALTER TABLE "edu_enrollment" ADD CONSTRAINT "edu_enrollment_user_id_course_id_01ab014c_uniq" UNIQUE ("user_id", "course_id");
--
-- Create index intq_course_diff_idx on field(s) course, difficulty of model interviewquestion
--
CREATE INDEX "intq_course_diff_idx" ON "edu_interviewquestion" ("course_id", "difficulty");
--
-- Create index intq_course_created_idx on field(s) course, created_at of model interviewquestion
--
CREATE INDEX "intq_course_created_idx" ON "edu_interviewquestion" ("course_id", "created_at");
--
-- Create index iqattempt_session_idx on field(s) session of model interviewquestionattempt
--
CREATE INDEX "iqattempt_session_idx" ON "edu_interviewquestionattempt" ("session_id");
--
-- Alter unique_together for interviewquestionattempt (1 constraint(s))
--
ALTER TABLE "edu_interviewquestionattempt" ADD CONSTRAINT "edu_interviewquestionatt_session_id_question_id_4931d653_uniq" UNIQUE ("session_id", "question_id");
--
-- Create index edu_course__user_id_914ec6_idx on field(s) user, is_completed of model courseprogress
--
CREATE INDEX "edu_course__user_id_914ec6_idx" ON "edu_course_progress" ("user_id", "is_completed");
--
-- Create index edu_course__course__370f92_idx on field(s) course, is_completed of model courseprogress
--
CREATE INDEX "edu_course__course__370f92_idx" ON "edu_course_progress" ("course_id", "is_completed");
--
-- Create index edu_course__course__d222d5_idx on field(s) course, progress_pct of model courseprogress
--
CREATE INDEX "edu_course__course__d222d5_idx" ON "edu_course_progress" ("course_id", "progress_pct");
--
-- Create index edu_course__last_ac_5ac72b_idx on field(s) last_accessed_at of model courseprogress
--
CREATE INDEX "edu_course__last_ac_5ac72b_idx" ON "edu_course_progress" ("last_accessed_at");
--
-- Alter unique_together for courseprogress (1 constraint(s))
--
ALTER TABLE "edu_course_progress" ADD CONSTRAINT "edu_course_progress_user_id_course_id_b1a34d4d_uniq" UNIQUE ("user_id", "course_id");
--
-- Create index edu_analyti_user_id_098aa5_idx on field(s) user, created_at of model analyticsevent
--
CREATE INDEX "edu_analyti_user_id_098aa5_idx" ON "edu_analytics_event" ("user_id", "created_at");
--
-- Create index edu_analyti_event_t_e1a35d_idx on field(s) event_type, created_at of model analyticsevent
--
CREATE INDEX "edu_analyti_event_t_e1a35d_idx" ON "edu_analytics_event" ("event_type", "created_at");
--
-- Create index edu_analyti_course__2f1dff_idx on field(s) course, event_type, created_at of model analyticsevent
--
CREATE INDEX "edu_analyti_course__2f1dff_idx" ON "edu_analytics_event" ("course_id", "event_type", "created_at");
--
-- Create index edu_analyti_user_id_6ae754_idx on field(s) user, event_type, created_at of model analyticsevent
--
CREATE INDEX "edu_analyti_user_id_6ae754_idx" ON "edu_analytics_event" ("user_id", "event_type", "created_at");
--
-- Create index edu_analyti_session_b4eac5_idx on field(s) session_id, created_at of model analyticsevent
--
CREATE INDEX "edu_analyti_session_b4eac5_idx" ON "edu_analytics_event" ("session_id", "created_at");
--
-- Create index edu_analyti_created_17cf6f_idx on field(s) created_at of model analyticsevent
--
CREATE INDEX "edu_analyti_created_17cf6f_idx" ON "edu_analytics_event" ("created_at");
--
-- Create index edu_analyti_lesson__5ea94a_idx on field(s) lesson, event_type of model analyticsevent
--
CREATE INDEX "edu_analyti_lesson__5ea94a_idx" ON "edu_analytics_event" ("lesson_id", "event_type");
--
-- Create index edu_lesson__lesson__eeafa6_idx on field(s) lesson, date of model lessonanalyticssummary
--
CREATE INDEX "edu_lesson__lesson__eeafa6_idx" ON "edu_lesson_analytics_summary" ("lesson_id", "date");
--
-- Create index edu_lesson__date_dd296e_idx on field(s) date of model lessonanalyticssummary
--
CREATE INDEX "edu_lesson__date_dd296e_idx" ON "edu_lesson_analytics_summary" ("date");
--
-- Alter unique_together for lessonanalyticssummary (1 constraint(s))
--
ALTER TABLE "edu_lesson_analytics_summary" ADD CONSTRAINT "edu_lesson_analytics_summary_lesson_id_date_ff7af76d_uniq" UNIQUE ("lesson_id", "date");
--
-- Create index edu_lesson__user_id_92e64a_idx on field(s) user, is_completed of model lessonprogress
--
CREATE INDEX "edu_lesson__user_id_92e64a_idx" ON "edu_lesson_progress" ("user_id", "is_completed");
--
-- Create index edu_lesson__lesson__987b65_idx on field(s) lesson, is_completed of model lessonprogress
--
CREATE INDEX "edu_lesson__lesson__987b65_idx" ON "edu_lesson_progress" ("lesson_id", "is_completed");
--
-- Create index edu_lesson__complet_fa87c2_idx on field(s) completed_at of model lessonprogress
--
CREATE INDEX "edu_lesson__complet_fa87c2_idx" ON "edu_lesson_progress" ("completed_at");
--
-- Create index edu_lesson__user_id_b723c7_idx on field(s) user, last_accessed_at of model lessonprogress
--
CREATE INDEX "edu_lesson__user_id_b723c7_idx" ON "edu_lesson_progress" ("user_id", "last_accessed_at");
--
-- Alter unique_together for lessonprogress (1 constraint(s))
--
ALTER TABLE "edu_lesson_progress" ADD CONSTRAINT "edu_lesson_progress_user_id_lesson_id_f6fbd3d8_uniq" UNIQUE ("user_id", "lesson_id");
--
-- Create index mcqa_question_user_idx on field(s) question, user of model mcqattempt
--
CREATE INDEX "mcqa_question_user_idx" ON "edu_mcqattempt" ("question_id", "user_id");
--
-- Create index mcqa_user_correct_idx on field(s) user, is_correct of model mcqattempt
--
CREATE INDEX "mcqa_user_correct_idx" ON "edu_mcqattempt" ("user_id", "is_correct");
--
-- Create constraint uniq_mcqa_user_question on model mcqattempt
--
ALTER TABLE "edu_mcqattempt" ADD CONSTRAINT "uniq_mcqa_user_question" UNIQUE ("user_id", "question_id");
--
-- Create index edu_module_course__0815da_idx on field(s) course, order of model module
--
CREATE INDEX "edu_module_course__0815da_idx" ON "edu_module" ("course_id", "order");
--
-- Create index mcqq_mod_testno_idx on field(s) module, mcq_test_no of model mcqquestion
--
CREATE INDEX "mcqq_mod_testno_idx" ON "edu_mcqquestion" ("module_id", "mcq_test_no");
--
-- Create index mcqq_mod_created_idx on field(s) module, created_at of model mcqquestion
--
CREATE INDEX "mcqq_mod_created_idx" ON "edu_mcqquestion" ("module_id", "created_at");
--
-- Create index edu_lesson_module__53cf97_idx on field(s) module, order of model lesson
--
CREATE INDEX "edu_lesson_module__53cf97_idx" ON "edu_lesson" ("module_id", "order");
--
-- Create index edu_lesson_lesson__3323d9_idx on field(s) lesson_type of model lesson
--
CREATE INDEX "edu_lesson_lesson__3323d9_idx" ON "edu_lesson" ("lesson_type");
--
-- Create index edu_lesson_is_prev_21e540_idx on field(s) is_preview of model lesson
--
CREATE INDEX "edu_lesson_is_prev_21e540_idx" ON "edu_lesson" ("is_preview");
--
-- Create index isess_user_role_idx on field(s) user, job_role of model interviewsession
--
CREATE INDEX "isess_user_role_idx" ON "edu_interviewsession" ("user_id", "job_role_id");
--
-- Create index isess_user_mod_idx on field(s) user, module of model interviewsession
--
CREATE INDEX "isess_user_mod_idx" ON "edu_interviewsession" ("user_id", "module_id");
--
-- Create index imcq_module_idx on field(s) module of model interviewmcqquestion
--
CREATE INDEX "imcq_module_idx" ON "edu_interviewmcqquestion" ("module_id");
--
-- Create index progq_course_diff_idx on field(s) course, difficulty of model programmingquestion
--
CREATE INDEX "progq_course_diff_idx" ON "edu_programmingquestion" ("course_id", "difficulty");
--
-- Create index progq_course_created_idx on field(s) course, created_at of model programmingquestion
--
CREATE INDEX "progq_course_created_idx" ON "edu_programmingquestion" ("course_id", "created_at");
--
-- Create index edu_course_status_b68e58_idx on field(s) status, is_free of model course
--
CREATE INDEX "edu_course_status_b68e58_idx" ON "edu_course" ("status", "is_free");
--
-- Create index edu_course_instruc_373e5f_idx on field(s) instructor, status of model course
--
CREATE INDEX "edu_course_instruc_373e5f_idx" ON "edu_course" ("instructor_id", "status");
--
-- Create index edu_course_publish_f9c91f_idx on field(s) published_at, status of model course
--
CREATE INDEX "edu_course_publish_f9c91f_idx" ON "edu_course" ("published_at", "status");
--
-- Create index edu_course_status_13a04e_idx on field(s) status, created_at of model course
--
CREATE INDEX "edu_course_status_13a04e_idx" ON "edu_course" ("status", "created_at");
--
-- Create index edu_user_ac_user_id_27f7cc_idx on field(s) user, date of model useractivitysummary
--
CREATE INDEX "edu_user_ac_user_id_27f7cc_idx" ON "edu_user_activity_summary" ("user_id", "date");
--
-- Create index edu_user_ac_date_12c87d_idx on field(s) date of model useractivitysummary
--
CREATE INDEX "edu_user_ac_date_12c87d_idx" ON "edu_user_activity_summary" ("date");
--
-- Alter unique_together for useractivitysummary (1 constraint(s))
--
ALTER TABLE "edu_user_activity_summary" ADD CONSTRAINT "edu_user_activity_summary_user_id_date_2f854a15_uniq" UNIQUE ("user_id", "date");
--
-- Create index edu_video_p_user_id_ea6648_idx on field(s) user, last_watched_at of model videoprogress
--
CREATE INDEX "edu_video_p_user_id_ea6648_idx" ON "edu_video_progress" ("user_id", "last_watched_at");
--
-- Create index edu_video_p_lesson__11b7c4_idx on field(s) lesson, watch_percentage of model videoprogress
--
CREATE INDEX "edu_video_p_lesson__11b7c4_idx" ON "edu_video_progress" ("lesson_id", "watch_percentage");
--
-- Alter unique_together for videoprogress (1 constraint(s))
--
ALTER TABLE "edu_video_progress" ADD CONSTRAINT "edu_video_progress_user_id_lesson_id_d370c75f_uniq" UNIQUE ("user_id", "lesson_id");
--
-- Create index edu_video_p_user_id_12277c_idx on field(s) user, lesson, created_at of model videoprogressevent
--
CREATE INDEX "edu_video_p_user_id_12277c_idx" ON "edu_video_progress_event" ("user_id", "lesson_id", "created_at");
--
-- Create index edu_video_p_lesson__267f9c_idx on field(s) lesson, event_type, created_at of model videoprogressevent
--
CREATE INDEX "edu_video_p_lesson__267f9c_idx" ON "edu_video_progress_event" ("lesson_id", "event_type", "created_at");
--
-- Create index edu_video_p_session_660250_idx on field(s) session_id of model videoprogressevent
--
CREATE INDEX "edu_video_p_session_660250_idx" ON "edu_video_progress_event" ("session_id");
--
-- Create index edu_video_p_created_a4715c_idx on field(s) created_at of model videoprogressevent
--
CREATE INDEX "edu_video_p_created_a4715c_idx" ON "edu_video_progress_event" ("created_at");
--
-- Create index yoy_acad_year_idx on field(s) academic_year of model yoyassessment
--
CREATE INDEX "yoy_acad_year_idx" ON "edu_yoyassessment" ("academic_year");
--
-- Create index yoy_sched_start_idx on field(s) scheduled_start of model yoyassessment
--
CREATE INDEX "yoy_sched_start_idx" ON "edu_yoyassessment" ("scheduled_start");
--
-- Create index yoyq_assessment_idx on field(s) assessment of model yoyquestion
--
CREATE INDEX "yoyq_assessment_idx" ON "edu_yoyquestion" ("assessment_id");
--
-- Create index yoysess_user_assess_idx on field(s) user, assessment of model yoysession
--
CREATE INDEX "yoysess_user_assess_idx" ON "edu_yoysession" ("user_id", "assessment_id");
--
-- Alter unique_together for yoyquestionattempt (1 constraint(s))
--
ALTER TABLE "edu_yoyquestionattempt" ADD CONSTRAINT "edu_yoyquestionattempt_session_id_question_id_647dfda2_uniq" UNIQUE ("session_id", "question_id");
CREATE INDEX "edu_lesson_created_at_fab92f0f" ON "edu_lesson" ("created_at");
CREATE INDEX "edu_lesson_deleted_at_74c65397" ON "edu_lesson" ("deleted_at");
CREATE INDEX "edu_lesson_lesson_type_a0235de7" ON "edu_lesson" ("lesson_type");
CREATE INDEX "edu_lesson_lesson_type_a0235de7_like" ON "edu_lesson" ("lesson_type" varchar_pattern_ops);
CREATE INDEX "edu_lesson_is_preview_17e18e76" ON "edu_lesson" ("is_preview");
CREATE INDEX "edu_tag_name_47222973_like" ON "edu_tag" ("name" varchar_pattern_ops);
CREATE INDEX "edu_tag_slug_a18c35e9_like" ON "edu_tag" ("slug" varchar_pattern_ops);
CREATE INDEX "edu_user_username_ff60864d_like" ON "edu_user" ("username" varchar_pattern_ops);
CREATE INDEX "edu_user_created_at_b57541e2" ON "edu_user" ("created_at");
CREATE INDEX "edu_user_email_75d2803e_like" ON "edu_user" ("email" varchar_pattern_ops);
CREATE INDEX "edu_user_role_17a90542" ON "edu_user" ("role");
CREATE INDEX "edu_user_role_17a90542_like" ON "edu_user" ("role" varchar_pattern_ops);
CREATE INDEX "edu_user_is_email_verified_23a606d3" ON "edu_user" ("is_email_verified");
CREATE INDEX "edu_user_last_seen_at_6ee96916" ON "edu_user" ("last_seen_at");
ALTER TABLE "edu_user_groups" ADD CONSTRAINT "edu_user_groups_user_id_group_id_b23c9db9_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "edu_user_groups" ADD CONSTRAINT "edu_user_groups_user_id_9e88a89a_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_user_groups" ADD CONSTRAINT "edu_user_groups_group_id_a42a294c_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_user_groups_user_id_9e88a89a" ON "edu_user_groups" ("user_id");
CREATE INDEX "edu_user_groups_group_id_a42a294c" ON "edu_user_groups" ("group_id");
ALTER TABLE "edu_user_user_permissions" ADD CONSTRAINT "edu_user_user_permissions_user_id_permission_id_46dcbeeb_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "edu_user_user_permissions" ADD CONSTRAINT "edu_user_user_permissions_user_id_629f2d55_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_user_user_permissions" ADD CONSTRAINT "edu_user_user_permis_permission_id_1b0f830f_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_user_user_permissions_user_id_629f2d55" ON "edu_user_user_permissions" ("user_id");
CREATE INDEX "edu_user_user_permissions_permission_id_1b0f830f" ON "edu_user_user_permissions" ("permission_id");
ALTER TABLE "edu_audit_log" ADD CONSTRAINT "edu_audit_log_actor_id_355139b4_fk_edu_user_id" FOREIGN KEY ("actor_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_audit_log_action_57f3794d" ON "edu_audit_log" ("action");
CREATE INDEX "edu_audit_log_action_57f3794d_like" ON "edu_audit_log" ("action" varchar_pattern_ops);
CREATE INDEX "edu_audit_log_resource_type_8217c187" ON "edu_audit_log" ("resource_type");
CREATE INDEX "edu_audit_log_resource_type_8217c187_like" ON "edu_audit_log" ("resource_type" varchar_pattern_ops);
CREATE INDEX "edu_audit_log_resource_id_4a45afc9" ON "edu_audit_log" ("resource_id");
CREATE INDEX "edu_audit_log_resource_id_4a45afc9_like" ON "edu_audit_log" ("resource_id" varchar_pattern_ops);
CREATE INDEX "edu_audit_log_created_at_237810c4" ON "edu_audit_log" ("created_at");
CREATE INDEX "edu_audit_log_actor_id_355139b4" ON "edu_audit_log" ("actor_id");
ALTER TABLE "edu_communitypost" ADD CONSTRAINT "edu_communitypost_author_id_f4383d71_fk_edu_user_id" FOREIGN KEY ("author_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_communitypost_author_id_f4383d71" ON "edu_communitypost" ("author_id");
ALTER TABLE "edu_course" ADD CONSTRAINT "edu_course_instructor_id_d9627605_fk_edu_user_id" FOREIGN KEY ("instructor_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_course_created_at_38ec05f0" ON "edu_course" ("created_at");
CREATE INDEX "edu_course_deleted_at_a254484f" ON "edu_course" ("deleted_at");
CREATE INDEX "edu_course_slug_73cb5e07_like" ON "edu_course" ("slug" varchar_pattern_ops);
CREATE INDEX "edu_course_is_free_5b41b315" ON "edu_course" ("is_free");
CREATE INDEX "edu_course_status_1d2c929e" ON "edu_course" ("status");
CREATE INDEX "edu_course_status_1d2c929e_like" ON "edu_course" ("status" varchar_pattern_ops);
CREATE INDEX "edu_course_published_at_e8eba769" ON "edu_course" ("published_at");
CREATE INDEX "edu_course_instructor_id_d9627605" ON "edu_course" ("instructor_id");
ALTER TABLE "edu_course_tags" ADD CONSTRAINT "edu_course_tags_course_id_tag_id_c48a4a78_uniq" UNIQUE ("course_id", "tag_id");
ALTER TABLE "edu_course_tags" ADD CONSTRAINT "edu_course_tags_course_id_617f74f5_fk_edu_course_id" FOREIGN KEY ("course_id") REFERENCES "edu_course" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_course_tags" ADD CONSTRAINT "edu_course_tags_tag_id_74210709_fk_edu_tag_id" FOREIGN KEY ("tag_id") REFERENCES "edu_tag" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_course_tags_course_id_617f74f5" ON "edu_course_tags" ("course_id");
CREATE INDEX "edu_course_tags_tag_id_74210709" ON "edu_course_tags" ("tag_id");
ALTER TABLE "edu_course_analytics_summary" ADD CONSTRAINT "edu_course_analytics_course_id_6d7bc7f7_fk_edu_cours" FOREIGN KEY ("course_id") REFERENCES "edu_course" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_course_analytics_summary_date_d91e0158" ON "edu_course_analytics_summary" ("date");
CREATE INDEX "edu_course_analytics_summary_course_id_6d7bc7f7" ON "edu_course_analytics_summary" ("course_id");
ALTER TABLE "edu_course_rating" ADD CONSTRAINT "edu_course_rating_course_id_029a7454_fk_edu_course_id" FOREIGN KEY ("course_id") REFERENCES "edu_course" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_course_rating" ADD CONSTRAINT "edu_course_rating_user_id_c300b37b_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_course_rating_created_at_097e1b5f" ON "edu_course_rating" ("created_at");
CREATE INDEX "edu_course_rating_course_id_029a7454" ON "edu_course_rating" ("course_id");
CREATE INDEX "edu_course_rating_user_id_c300b37b" ON "edu_course_rating" ("user_id");
ALTER TABLE "edu_dau" ADD CONSTRAINT "edu_dau_user_id_8255d766_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_dau_date_2b0da1b7" ON "edu_dau" ("date");
CREATE INDEX "edu_dau_user_id_8255d766" ON "edu_dau" ("user_id");
ALTER TABLE "edu_emailverificationtoken" ADD CONSTRAINT "edu_emailverificationtoken_user_id_638c7a82_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_enrollment" ADD CONSTRAINT "edu_enrollment_course_id_2226a561_fk_edu_course_id" FOREIGN KEY ("course_id") REFERENCES "edu_course" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_enrollment" ADD CONSTRAINT "edu_enrollment_user_id_4eb443cc_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_enrollment_created_at_ab353c7f" ON "edu_enrollment" ("created_at");
CREATE INDEX "edu_enrollment_status_073967f7" ON "edu_enrollment" ("status");
CREATE INDEX "edu_enrollment_status_073967f7_like" ON "edu_enrollment" ("status" varchar_pattern_ops);
CREATE INDEX "edu_enrollment_payment_status_1105fe69" ON "edu_enrollment" ("payment_status");
CREATE INDEX "edu_enrollment_payment_status_1105fe69_like" ON "edu_enrollment" ("payment_status" varchar_pattern_ops);
CREATE INDEX "edu_enrollment_enrolled_at_5cebaa19" ON "edu_enrollment" ("enrolled_at");
CREATE INDEX "edu_enrollment_last_accessed_at_061d7e02" ON "edu_enrollment" ("last_accessed_at");
CREATE INDEX "edu_enrollment_completed_at_47f2e120" ON "edu_enrollment" ("completed_at");
CREATE INDEX "edu_enrollment_course_id_2226a561" ON "edu_enrollment" ("course_id");
CREATE INDEX "edu_enrollment_user_id_4eb443cc" ON "edu_enrollment" ("user_id");
ALTER TABLE "edu_interviewquestion" ADD CONSTRAINT "edu_interviewquestion_course_id_a25b9e6b_fk_edu_course_id" FOREIGN KEY ("course_id") REFERENCES "edu_course" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_interviewquestion_course_id_a25b9e6b" ON "edu_interviewquestion" ("course_id");
ALTER TABLE "edu_interviewquestion_is_bookmarked_by" ADD CONSTRAINT "edu_interviewquestion_is_interviewquestion_id_use_9e637445_uniq" UNIQUE ("interviewquestion_id", "user_id");
ALTER TABLE "edu_interviewquestion_is_bookmarked_by" ADD CONSTRAINT "edu_interviewquestio_interviewquestion_id_86a7922b_fk_edu_inter" FOREIGN KEY ("interviewquestion_id") REFERENCES "edu_interviewquestion" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_interviewquestion_is_bookmarked_by" ADD CONSTRAINT "edu_interviewquestio_user_id_c3ac7e43_fk_edu_user_" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_interviewquestion_is_b_interviewquestion_id_86a7922b" ON "edu_interviewquestion_is_bookmarked_by" ("interviewquestion_id");
CREATE INDEX "edu_interviewquestion_is_bookmarked_by_user_id_c3ac7e43" ON "edu_interviewquestion_is_bookmarked_by" ("user_id");
ALTER TABLE "edu_interviewanswer" ADD CONSTRAINT "edu_interviewanswer_question_id_ab66940e_fk_edu_inter" FOREIGN KEY ("question_id") REFERENCES "edu_interviewquestion" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_interviewanswer_question_id_ab66940e" ON "edu_interviewanswer" ("question_id");
ALTER TABLE "edu_interviewsession" ADD CONSTRAINT "edu_interviewsession_user_id_f22d0c18_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_interviewsession" ADD CONSTRAINT "edu_interviewsession_job_role_id_835dafa0_fk_edu_jobrole_id" FOREIGN KEY ("job_role_id") REFERENCES "edu_jobrole" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_interviewsession_user_id_f22d0c18" ON "edu_interviewsession" ("user_id");
CREATE INDEX "edu_interviewsession_job_role_id_835dafa0" ON "edu_interviewsession" ("job_role_id");
ALTER TABLE "edu_interviewquestionattempt" ADD CONSTRAINT "edu_interviewquestio_question_id_cf00e1c0_fk_edu_inter" FOREIGN KEY ("question_id") REFERENCES "edu_interviewmcqquestion" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_interviewquestionattempt" ADD CONSTRAINT "edu_interviewquestio_session_id_eeee40f3_fk_edu_inter" FOREIGN KEY ("session_id") REFERENCES "edu_interviewsession" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_interviewquestionattempt_question_id_cf00e1c0" ON "edu_interviewquestionattempt" ("question_id");
CREATE INDEX "edu_interviewquestionattempt_session_id_eeee40f3" ON "edu_interviewquestionattempt" ("session_id");
ALTER TABLE "edu_discussioncomment" ADD CONSTRAINT "edu_discussioncomment_author_id_5aab4cfe_fk_edu_user_id" FOREIGN KEY ("author_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_discussioncomment" ADD CONSTRAINT "edu_discussioncommen_reply_to_id_601b7835_fk_edu_discu" FOREIGN KEY ("reply_to_id") REFERENCES "edu_discussioncomment" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_discussioncomment" ADD CONSTRAINT "edu_discussioncomment_lesson_id_1df4fd0d_fk_edu_lesson_id" FOREIGN KEY ("lesson_id") REFERENCES "edu_lesson" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_discussioncomment_author_id_5aab4cfe" ON "edu_discussioncomment" ("author_id");
CREATE INDEX "edu_discussioncomment_reply_to_id_601b7835" ON "edu_discussioncomment" ("reply_to_id");
CREATE INDEX "edu_discussioncomment_lesson_id_1df4fd0d" ON "edu_discussioncomment" ("lesson_id");
ALTER TABLE "edu_course_progress" ADD CONSTRAINT "edu_course_progress_course_id_fc4229fc_fk_edu_course_id" FOREIGN KEY ("course_id") REFERENCES "edu_course" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_course_progress" ADD CONSTRAINT "edu_course_progress_user_id_cdbc8d08_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_course_progress" ADD CONSTRAINT "edu_course_progress_last_accessed_lesson_600d0c7a_fk_edu_lesso" FOREIGN KEY ("last_accessed_lesson_id") REFERENCES "edu_lesson" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_course_progress_created_at_b9c2e344" ON "edu_course_progress" ("created_at");
CREATE INDEX "edu_course_progress_last_accessed_at_18b27844" ON "edu_course_progress" ("last_accessed_at");
CREATE INDEX "edu_course_progress_is_completed_830d1f8e" ON "edu_course_progress" ("is_completed");
CREATE INDEX "edu_course_progress_course_id_fc4229fc" ON "edu_course_progress" ("course_id");
CREATE INDEX "edu_course_progress_user_id_cdbc8d08" ON "edu_course_progress" ("user_id");
CREATE INDEX "edu_course_progress_last_accessed_lesson_id_600d0c7a" ON "edu_course_progress" ("last_accessed_lesson_id");
ALTER TABLE "edu_analytics_event" ADD CONSTRAINT "edu_analytics_event_user_id_48c80988_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_analytics_event" ADD CONSTRAINT "edu_analytics_event_course_id_ae715f89_fk_edu_course_id" FOREIGN KEY ("course_id") REFERENCES "edu_course" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_analytics_event" ADD CONSTRAINT "edu_analytics_event_lesson_id_d44dcf72_fk_edu_lesson_id" FOREIGN KEY ("lesson_id") REFERENCES "edu_lesson" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_analytics_event_event_type_2d57b382" ON "edu_analytics_event" ("event_type");
CREATE INDEX "edu_analytics_event_event_type_2d57b382_like" ON "edu_analytics_event" ("event_type" varchar_pattern_ops);
CREATE INDEX "edu_analytics_event_session_id_5fc9bf1f" ON "edu_analytics_event" ("session_id");
CREATE INDEX "edu_analytics_event_session_id_5fc9bf1f_like" ON "edu_analytics_event" ("session_id" varchar_pattern_ops);
CREATE INDEX "edu_analytics_event_created_at_1c994bdd" ON "edu_analytics_event" ("created_at");
CREATE INDEX "edu_analytics_event_user_id_48c80988" ON "edu_analytics_event" ("user_id");
CREATE INDEX "edu_analytics_event_course_id_ae715f89" ON "edu_analytics_event" ("course_id");
CREATE INDEX "edu_analytics_event_lesson_id_d44dcf72" ON "edu_analytics_event" ("lesson_id");
ALTER TABLE "edu_lesson_analytics_summary" ADD CONSTRAINT "edu_lesson_analytics_lesson_id_4cb8f9de_fk_edu_lesso" FOREIGN KEY ("lesson_id") REFERENCES "edu_lesson" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_lesson_analytics_summary_date_a2c7160b" ON "edu_lesson_analytics_summary" ("date");
CREATE INDEX "edu_lesson_analytics_summary_lesson_id_4cb8f9de" ON "edu_lesson_analytics_summary" ("lesson_id");
ALTER TABLE "edu_lesson_progress" ADD CONSTRAINT "edu_lesson_progress_lesson_id_68a76a7b_fk_edu_lesson_id" FOREIGN KEY ("lesson_id") REFERENCES "edu_lesson" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_lesson_progress" ADD CONSTRAINT "edu_lesson_progress_user_id_9ea7bcbd_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_lesson_progress_created_at_089cb193" ON "edu_lesson_progress" ("created_at");
CREATE INDEX "edu_lesson_progress_is_completed_63357336" ON "edu_lesson_progress" ("is_completed");
CREATE INDEX "edu_lesson_progress_completed_at_c4834a4c" ON "edu_lesson_progress" ("completed_at");
CREATE INDEX "edu_lesson_progress_lesson_id_68a76a7b" ON "edu_lesson_progress" ("lesson_id");
CREATE INDEX "edu_lesson_progress_user_id_9ea7bcbd" ON "edu_lesson_progress" ("user_id");
ALTER TABLE "edu_mcqattempt" ADD CONSTRAINT "edu_mcqattempt_user_id_a09f9ef4_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_mcqattempt" ADD CONSTRAINT "edu_mcqattempt_question_id_9419ec0f_fk_edu_mcqquestion_id" FOREIGN KEY ("question_id") REFERENCES "edu_mcqquestion" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_mcqattempt_user_id_a09f9ef4" ON "edu_mcqattempt" ("user_id");
CREATE INDEX "edu_mcqattempt_question_id_9419ec0f" ON "edu_mcqattempt" ("question_id");
ALTER TABLE "edu_miniproject" ADD CONSTRAINT "edu_miniproject_course_id_cd354389_fk_edu_course_id" FOREIGN KEY ("course_id") REFERENCES "edu_course" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_miniproject_course_id_cd354389" ON "edu_miniproject" ("course_id");
ALTER TABLE "edu_module" ADD CONSTRAINT "edu_module_course_id_c86dbab2_fk_edu_course_id" FOREIGN KEY ("course_id") REFERENCES "edu_course" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_module_created_at_26638e5e" ON "edu_module" ("created_at");
CREATE INDEX "edu_module_deleted_at_fa9ccbe8" ON "edu_module" ("deleted_at");
CREATE INDEX "edu_module_course_id_c86dbab2" ON "edu_module" ("course_id");
CREATE INDEX "edu_mcqquestion_module_id_f47b2436" ON "edu_mcqquestion" ("module_id");
CREATE INDEX "edu_lesson_module_id_22be4787" ON "edu_lesson" ("module_id");
ALTER TABLE "edu_jobrole_modules" ADD CONSTRAINT "edu_jobrole_modules_jobrole_id_module_id_6565c141_uniq" UNIQUE ("jobrole_id", "module_id");
ALTER TABLE "edu_jobrole_modules" ADD CONSTRAINT "edu_jobrole_modules_jobrole_id_2236c33a_fk_edu_jobrole_id" FOREIGN KEY ("jobrole_id") REFERENCES "edu_jobrole" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_jobrole_modules" ADD CONSTRAINT "edu_jobrole_modules_module_id_7f157710_fk_edu_module_id" FOREIGN KEY ("module_id") REFERENCES "edu_module" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_jobrole_modules_jobrole_id_2236c33a" ON "edu_jobrole_modules" ("jobrole_id");
CREATE INDEX "edu_jobrole_modules_module_id_7f157710" ON "edu_jobrole_modules" ("module_id");
CREATE INDEX "edu_interviewsession_module_id_1994c7b1" ON "edu_interviewsession" ("module_id");
CREATE INDEX "edu_interviewmcqquestion_module_id_73f19670" ON "edu_interviewmcqquestion" ("module_id");
ALTER TABLE "edu_passwordresettoken" ADD CONSTRAINT "edu_passwordresettoken_user_id_8b733ae1_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_programmingquestion" ADD CONSTRAINT "edu_programmingquestion_course_id_50aa860e_fk_edu_course_id" FOREIGN KEY ("course_id") REFERENCES "edu_course" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_programmingquestion_course_id_50aa860e" ON "edu_programmingquestion" ("course_id");
ALTER TABLE "edu_studymaterial" ADD CONSTRAINT "edu_studymaterial_course_id_e986dbdb_fk_edu_course_id" FOREIGN KEY ("course_id") REFERENCES "edu_course" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_studymaterial_course_id_e986dbdb" ON "edu_studymaterial" ("course_id");
ALTER TABLE "edu_user_activity_summary" ADD CONSTRAINT "edu_user_activity_summary_user_id_6d1dbba7_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_user_activity_summary_date_d0b686b5" ON "edu_user_activity_summary" ("date");
CREATE INDEX "edu_user_activity_summary_user_id_6d1dbba7" ON "edu_user_activity_summary" ("user_id");
ALTER TABLE "edu_video_progress" ADD CONSTRAINT "edu_video_progress_lesson_id_c85310e9_fk_edu_lesson_id" FOREIGN KEY ("lesson_id") REFERENCES "edu_lesson" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_video_progress" ADD CONSTRAINT "edu_video_progress_user_id_bbc64b88_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_video_progress_created_at_8e3795bd" ON "edu_video_progress" ("created_at");
CREATE INDEX "edu_video_progress_last_watched_at_88569635" ON "edu_video_progress" ("last_watched_at");
CREATE INDEX "edu_video_progress_lesson_id_c85310e9" ON "edu_video_progress" ("lesson_id");
CREATE INDEX "edu_video_progress_user_id_bbc64b88" ON "edu_video_progress" ("user_id");
ALTER TABLE "edu_video_progress_event" ADD CONSTRAINT "edu_video_progress_event_lesson_id_14144a10_fk_edu_lesson_id" FOREIGN KEY ("lesson_id") REFERENCES "edu_lesson" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_video_progress_event" ADD CONSTRAINT "edu_video_progress_event_user_id_9f2bd705_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_video_progress_event_event_type_2779e4b3" ON "edu_video_progress_event" ("event_type");
CREATE INDEX "edu_video_progress_event_event_type_2779e4b3_like" ON "edu_video_progress_event" ("event_type" varchar_pattern_ops);
CREATE INDEX "edu_video_progress_event_session_id_2af29406" ON "edu_video_progress_event" ("session_id");
CREATE INDEX "edu_video_progress_event_session_id_2af29406_like" ON "edu_video_progress_event" ("session_id" varchar_pattern_ops);
CREATE INDEX "edu_video_progress_event_created_at_462beca0" ON "edu_video_progress_event" ("created_at");
CREATE INDEX "edu_video_progress_event_lesson_id_14144a10" ON "edu_video_progress_event" ("lesson_id");
CREATE INDEX "edu_video_progress_event_user_id_9f2bd705" ON "edu_video_progress_event" ("user_id");
ALTER TABLE "edu_yoyassessment" ADD CONSTRAINT "edu_yoyassessment_module_id_384e894d_fk_edu_module_id" FOREIGN KEY ("module_id") REFERENCES "edu_module" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_yoyassessment_module_id_384e894d" ON "edu_yoyassessment" ("module_id");
ALTER TABLE "edu_yoyquestion" ADD CONSTRAINT "edu_yoyquestion_assessment_id_0d0df9fc_fk_edu_yoyassessment_id" FOREIGN KEY ("assessment_id") REFERENCES "edu_yoyassessment" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_yoyquestion_assessment_id_0d0df9fc" ON "edu_yoyquestion" ("assessment_id");
ALTER TABLE "edu_yoysession" ADD CONSTRAINT "edu_yoysession_assessment_id_0357f970_fk_edu_yoyassessment_id" FOREIGN KEY ("assessment_id") REFERENCES "edu_yoyassessment" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_yoysession" ADD CONSTRAINT "edu_yoysession_user_id_8912214a_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_yoysession_assessment_id_0357f970" ON "edu_yoysession" ("assessment_id");
CREATE INDEX "edu_yoysession_user_id_8912214a" ON "edu_yoysession" ("user_id");
ALTER TABLE "edu_yoyquestionattempt" ADD CONSTRAINT "edu_yoyquestionattem_question_id_ba531438_fk_edu_yoyqu" FOREIGN KEY ("question_id") REFERENCES "edu_yoyquestion" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_yoyquestionattempt" ADD CONSTRAINT "edu_yoyquestionattempt_session_id_3b09453a_fk_edu_yoysession_id" FOREIGN KEY ("session_id") REFERENCES "edu_yoysession" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_yoyquestionattempt_question_id_ba531438" ON "edu_yoyquestionattempt" ("question_id");
CREATE INDEX "edu_yoyquestionattempt_session_id_3b09453a" ON "edu_yoyquestionattempt" ("session_id");
COMMIT;

-- ===== admin.0001_initial =====
BEGIN;
--
-- Create model LogEntry
--
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" uuid NOT NULL);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
COMMIT;

-- ===== admin.0002_logentry_remove_auto_add =====
BEGIN;
--
-- Alter field action_time on logentry
--
-- (no-op)
COMMIT;

-- ===== admin.0003_logentry_add_action_flag_choices =====
BEGIN;
--
-- Alter field action_flag on logentry
--
-- (no-op)
COMMIT;

-- ===== edu.0003_career_interview_preparation =====
BEGIN;
--
-- Create model EngineeringBranch
--
CREATE TABLE "edu_engineeringbranch" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL UNIQUE, "description" text NOT NULL, "image" varchar(2048) NOT NULL, "is_active" boolean NOT NULL);
--
-- Create model Domain
--
CREATE TABLE "edu_domain" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL, "overview" text NOT NULL, "technologies" text NOT NULL, "top_recruiters" text NOT NULL, "average_salary" varchar(255) NOT NULL, "demand_level" varchar(100) NOT NULL, "future_scope" text NOT NULL, "is_active" boolean NOT NULL, "branch_id" uuid NOT NULL);
--
-- Create constraint unique_branch_domain on model domain
--
ALTER TABLE "edu_domain" ADD CONSTRAINT "unique_branch_domain" UNIQUE ("branch_id", "name");
--
-- Add field domain to jobrole
--
ALTER TABLE "edu_jobrole" ADD COLUMN "domain_id" uuid NULL CONSTRAINT "edu_jobrole_domain_id_db7fc085_fk_edu_domain_id" REFERENCES "edu_domain"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "edu_jobrole_domain_id_db7fc085_fk_edu_domain_id" IMMEDIATE;
--
-- Add field responsibilities to jobrole
--
ALTER TABLE "edu_jobrole" ADD COLUMN "responsibilities" text DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobrole" ALTER COLUMN "responsibilities" DROP DEFAULT;
--
-- Add field required_skills to jobrole
--
ALTER TABLE "edu_jobrole" ADD COLUMN "required_skills" text DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobrole" ALTER COLUMN "required_skills" DROP DEFAULT;
--
-- Add field salary to jobrole
--
ALTER TABLE "edu_jobrole" ADD COLUMN "salary" varchar(255) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobrole" ALTER COLUMN "salary" DROP DEFAULT;
--
-- Add field recruiters to jobrole
--
ALTER TABLE "edu_jobrole" ADD COLUMN "recruiters" text DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobrole" ALTER COLUMN "recruiters" DROP DEFAULT;
--
-- Add field demand_level to jobrole
--
ALTER TABLE "edu_jobrole" ADD COLUMN "demand_level" varchar(100) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobrole" ALTER COLUMN "demand_level" DROP DEFAULT;
--
-- Add field is_active to jobrole
--
ALTER TABLE "edu_jobrole" ADD COLUMN "is_active" boolean DEFAULT true NOT NULL;
ALTER TABLE "edu_jobrole" ALTER COLUMN "is_active" DROP DEFAULT;
--
-- Create model Assessment
--
CREATE TABLE "edu_assessment" ("id" uuid NOT NULL PRIMARY KEY, "title" varchar(255) NOT NULL, "duration" integer NOT NULL CHECK ("duration" >= 0), "passing_marks" integer NOT NULL CHECK ("passing_marks" >= 0), "total_marks" integer NOT NULL CHECK ("total_marks" >= 0), "is_active" boolean NOT NULL, "job_role_id" uuid NOT NULL);
--
-- Create model AssessmentSection
--
CREATE TABLE "edu_assessmentsection" ("id" uuid NOT NULL PRIMARY KEY, "title" varchar(255) NOT NULL, "display_order" integer NOT NULL CHECK ("display_order" >= 0), "assessment_id" uuid NOT NULL);
--
-- Create constraint unique_assessment_section_order on model assessmentsection
--
ALTER TABLE "edu_assessmentsection" ADD CONSTRAINT "unique_assessment_section_order" UNIQUE ("assessment_id", "display_order");
--
-- Create model CareerMCQQuestion
--
CREATE TABLE "edu_careermcqquestion" ("id" uuid NOT NULL PRIMARY KEY, "question" text NOT NULL, "option_a" varchar(500) NOT NULL, "option_b" varchar(500) NOT NULL, "option_c" varchar(500) NOT NULL, "option_d" varchar(500) NOT NULL, "correct_option" varchar(1) NOT NULL, "explanation" text NOT NULL, "marks" integer NOT NULL CHECK ("marks" >= 0), "display_order" integer NOT NULL CHECK ("display_order" >= 0), "section_id" uuid NOT NULL);
--
-- Create constraint unique_section_question_order on model careermcqquestion
--
ALTER TABLE "edu_careermcqquestion" ADD CONSTRAINT "unique_section_question_order" UNIQUE ("section_id", "display_order");
--
-- Create model AssessmentAttempt
--
CREATE TABLE "edu_assessmentattempt" ("id" uuid NOT NULL PRIMARY KEY, "total_questions" integer NOT NULL CHECK ("total_questions" >= 0), "correct_answers" integer NOT NULL CHECK ("correct_answers" >= 0), "score" integer NOT NULL CHECK ("score" >= 0), "percentage" numeric(5, 2) NOT NULL, "passed" boolean NOT NULL, "submitted_at" timestamp with time zone NOT NULL, "assessment_id" uuid NOT NULL, "user_id" uuid NOT NULL);
CREATE INDEX "edu_engineeringbranch_name_15f3136c_like" ON "edu_engineeringbranch" ("name" varchar_pattern_ops);
ALTER TABLE "edu_domain" ADD CONSTRAINT "edu_domain_branch_id_5a53b73a_fk_edu_engineeringbranch_id" FOREIGN KEY ("branch_id") REFERENCES "edu_engineeringbranch" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_domain_branch_id_5a53b73a" ON "edu_domain" ("branch_id");
CREATE INDEX "edu_jobrole_domain_id_db7fc085" ON "edu_jobrole" ("domain_id");
ALTER TABLE "edu_assessment" ADD CONSTRAINT "edu_assessment_job_role_id_676ce668_fk_edu_jobrole_id" FOREIGN KEY ("job_role_id") REFERENCES "edu_jobrole" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_assessment_job_role_id_676ce668" ON "edu_assessment" ("job_role_id");
ALTER TABLE "edu_assessmentsection" ADD CONSTRAINT "edu_assessmentsectio_assessment_id_2dfeeba2_fk_edu_asses" FOREIGN KEY ("assessment_id") REFERENCES "edu_assessment" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_assessmentsection_assessment_id_2dfeeba2" ON "edu_assessmentsection" ("assessment_id");
ALTER TABLE "edu_careermcqquestion" ADD CONSTRAINT "edu_careermcqquestio_section_id_c316f8b3_fk_edu_asses" FOREIGN KEY ("section_id") REFERENCES "edu_assessmentsection" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_careermcqquestion_section_id_c316f8b3" ON "edu_careermcqquestion" ("section_id");
ALTER TABLE "edu_assessmentattempt" ADD CONSTRAINT "edu_assessmentattemp_assessment_id_e045a73f_fk_edu_asses" FOREIGN KEY ("assessment_id") REFERENCES "edu_assessment" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_assessmentattempt" ADD CONSTRAINT "edu_assessmentattempt_user_id_a80a08a7_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_assessmentattempt_assessment_id_e045a73f" ON "edu_assessmentattempt" ("assessment_id");
CREATE INDEX "edu_assessmentattempt_user_id_a80a08a7" ON "edu_assessmentattempt" ("user_id");
COMMIT;

-- ===== edu.0004_sectionattempt =====
BEGIN;
--
-- Create model SectionAttempt
--
CREATE TABLE "edu_sectionattempt" ("id" uuid NOT NULL PRIMARY KEY, "attempt_number" integer NOT NULL CHECK ("attempt_number" >= 0), "total_questions" integer NOT NULL CHECK ("total_questions" >= 0), "correct_answers" integer NOT NULL CHECK ("correct_answers" >= 0), "score" integer NOT NULL CHECK ("score" >= 0), "total_marks" integer NOT NULL CHECK ("total_marks" >= 0), "percentage" numeric(5, 2) NOT NULL, "submitted_at" timestamp with time zone NOT NULL, "section_id" uuid NOT NULL, "user_id" uuid NOT NULL);
--
-- Create constraint unique_section_attempt_number on model sectionattempt
--
ALTER TABLE "edu_sectionattempt" ADD CONSTRAINT "unique_section_attempt_number" UNIQUE ("user_id", "section_id", "attempt_number");
--
-- Create index section_attempt_user_idx on field(s) user, section of model sectionattempt
--
CREATE INDEX "section_attempt_user_idx" ON "edu_sectionattempt" ("user_id", "section_id");
ALTER TABLE "edu_sectionattempt" ADD CONSTRAINT "edu_sectionattempt_section_id_c5ac19a9_fk_edu_asses" FOREIGN KEY ("section_id") REFERENCES "edu_assessmentsection" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_sectionattempt" ADD CONSTRAINT "edu_sectionattempt_user_id_38e0b065_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_sectionattempt_section_id_c5ac19a9" ON "edu_sectionattempt" ("section_id");
CREATE INDEX "edu_sectionattempt_user_id_38e0b065" ON "edu_sectionattempt" ("user_id");
COMMIT;

-- ===== edu.0005_company_jobopening =====
BEGIN;
--
-- Create model Company
--
CREATE TABLE "edu_company" ("id" uuid NOT NULL PRIMARY KEY, "name" varchar(255) NOT NULL UNIQUE, "careers_page_url" varchar(1000) NOT NULL, "logo_url" varchar(1000) NOT NULL, "is_active" boolean NOT NULL, "last_scraped_at" timestamp with time zone NULL, "created_at" timestamp with time zone NOT NULL);
--
-- Create model JobOpening
--
CREATE TABLE "edu_jobopening" ("id" uuid NOT NULL PRIMARY KEY, "title" varchar(500) NOT NULL, "location" varchar(255) NOT NULL, "description" text NOT NULL, "apply_url" varchar(1000) NOT NULL, "posted_date" date NULL, "content_hash" varchar(64) NOT NULL, "is_active" boolean NOT NULL, "scraped_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "company_id" uuid NOT NULL, CONSTRAINT "unique_company_job_hash" UNIQUE ("company_id", "content_hash"));
CREATE INDEX "edu_company_name_ab1a7ac3_like" ON "edu_company" ("name" varchar_pattern_ops);
ALTER TABLE "edu_jobopening" ADD CONSTRAINT "edu_jobopening_company_id_3fb40db0_fk_edu_company_id" FOREIGN KEY ("company_id") REFERENCES "edu_company" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_jobopening_content_hash_7f3d1e55" ON "edu_jobopening" ("content_hash");
CREATE INDEX "edu_jobopening_content_hash_7f3d1e55_like" ON "edu_jobopening" ("content_hash" varchar_pattern_ops);
CREATE INDEX "edu_jobopening_company_id_3fb40db0" ON "edu_jobopening" ("company_id");
COMMIT;

-- ===== edu.0006_jobsynclog_savedjob_alter_jobopening_options_and_more =====
BEGIN;
--
-- Create model JobSyncLog
--
CREATE TABLE "edu_jobsynclog" ("id" uuid NOT NULL PRIMARY KEY, "status" varchar(20) NOT NULL, "started_at" timestamp with time zone NOT NULL, "completed_at" timestamp with time zone NULL, "jobs_received" integer NOT NULL CHECK ("jobs_received" >= 0), "jobs_created" integer NOT NULL CHECK ("jobs_created" >= 0), "jobs_updated" integer NOT NULL CHECK ("jobs_updated" >= 0), "jobs_deactivated" integer NOT NULL CHECK ("jobs_deactivated" >= 0), "error_message" text NOT NULL);
--
-- Create model SavedJob
--
CREATE TABLE "edu_savedjob" ("id" uuid NOT NULL PRIMARY KEY, "created_at" timestamp with time zone NOT NULL);
--
-- Change Meta options on jobopening
--
-- (no-op)
--
-- Rename field last_scraped_at on company to last_synced_at
--
ALTER TABLE "edu_company" RENAME COLUMN "last_scraped_at" TO "last_synced_at";
--
-- Rename field scraped_at on jobopening to first_seen_at
--
ALTER TABLE "edu_jobopening" RENAME COLUMN "scraped_at" TO "first_seen_at";
--
-- Add field api_endpoint to company
--
ALTER TABLE "edu_company" ADD COLUMN "api_endpoint" varchar(1000) DEFAULT '' NOT NULL;
ALTER TABLE "edu_company" ALTER COLUMN "api_endpoint" DROP DEFAULT;
--
-- Add field ats_domain to company
--
ALTER TABLE "edu_company" ADD COLUMN "ats_domain" varchar(255) DEFAULT '' NOT NULL;
ALTER TABLE "edu_company" ALTER COLUMN "ats_domain" DROP DEFAULT;
--
-- Add field ats_platform to company
--
ALTER TABLE "edu_company" ADD COLUMN "ats_platform" varchar(120) DEFAULT '' NOT NULL;
ALTER TABLE "edu_company" ALTER COLUMN "ats_platform" DROP DEFAULT;
--
-- Add field ats_site_name to company
--
ALTER TABLE "edu_company" ADD COLUMN "ats_site_name" varchar(120) DEFAULT '' NOT NULL;
ALTER TABLE "edu_company" ALTER COLUMN "ats_site_name" DROP DEFAULT;
--
-- Add field company_logo to company
--
ALTER TABLE "edu_company" ADD COLUMN "company_logo" varchar(100) DEFAULT '' NOT NULL;
ALTER TABLE "edu_company" ALTER COLUMN "company_logo" DROP DEFAULT;
--
-- Add field country to company
--
ALTER TABLE "edu_company" ADD COLUMN "country" varchar(120) DEFAULT '' NOT NULL;
ALTER TABLE "edu_company" ALTER COLUMN "country" DROP DEFAULT;
--
-- Add field data_collection_method to company
--
ALTER TABLE "edu_company" ADD COLUMN "data_collection_method" varchar(40) DEFAULT 'not_identified' NOT NULL;
ALTER TABLE "edu_company" ALTER COLUMN "data_collection_method" DROP DEFAULT;
--
-- Add field description to company
--
ALTER TABLE "edu_company" ADD COLUMN "description" text DEFAULT '' NOT NULL;
ALTER TABLE "edu_company" ALTER COLUMN "description" DROP DEFAULT;
--
-- Add field headquarters to company
--
ALTER TABLE "edu_company" ADD COLUMN "headquarters" varchar(255) DEFAULT '' NOT NULL;
ALTER TABLE "edu_company" ALTER COLUMN "headquarters" DROP DEFAULT;
--
-- Add field industry to company
--
ALTER TABLE "edu_company" ADD COLUMN "industry" varchar(255) DEFAULT '' NOT NULL;
ALTER TABLE "edu_company" ALTER COLUMN "industry" DROP DEFAULT;
--
-- Add field last_successful_sync_at to company
--
ALTER TABLE "edu_company" ADD COLUMN "last_successful_sync_at" timestamp with time zone NULL;
--
-- Add field official_website to company
--
ALTER TABLE "edu_company" ADD COLUMN "official_website" varchar(1000) DEFAULT '' NOT NULL;
ALTER TABLE "edu_company" ALTER COLUMN "official_website" DROP DEFAULT;
--
-- Add field slug to company
--
ALTER TABLE "edu_company" ADD COLUMN "slug" varchar(280) NULL UNIQUE;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Add field sync_error to company
--
ALTER TABLE "edu_company" ADD COLUMN "sync_error" text DEFAULT '' NOT NULL;
ALTER TABLE "edu_company" ALTER COLUMN "sync_error" DROP DEFAULT;
--
-- Add field sync_status to company
--
ALTER TABLE "edu_company" ADD COLUMN "sync_status" varchar(20) DEFAULT 'never' NOT NULL;
ALTER TABLE "edu_company" ALTER COLUMN "sync_status" DROP DEFAULT;
--
-- Add field updated_at to company
--
ALTER TABLE "edu_company" ADD COLUMN "updated_at" timestamp with time zone DEFAULT '2026-07-24T14:40:31.004167+00:00'::timestamptz NULL;
ALTER TABLE "edu_company" ALTER COLUMN "updated_at" DROP DEFAULT;
--
-- Add field application_deadline to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "application_deadline" date NULL;
--
-- Add field city to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "city" varchar(120) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "city" DROP DEFAULT;
--
-- Add field country to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "country" varchar(120) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "country" DROP DEFAULT;
--
-- Add field data_verification_status to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "data_verification_status" varchar(80) DEFAULT 'Not Confirmed' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "data_verification_status" DROP DEFAULT;
--
-- Add field department to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "department" varchar(255) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "department" DROP DEFAULT;
--
-- Add field eligible_branches to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "eligible_branches" jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "eligible_branches" DROP DEFAULT;
--
-- Add field eligible_graduation_years to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "eligible_graduation_years" jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "eligible_graduation_years" DROP DEFAULT;
--
-- Add field experience_display to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "experience_display" varchar(120) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "experience_display" DROP DEFAULT;
--
-- Add field external_job_id to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "external_job_id" varchar(255) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "external_job_id" DROP DEFAULT;
--
-- Alter field first_seen_at on jobopening
--
-- (no-op)
--
-- Add field job_category to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "job_category" varchar(255) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "job_category" DROP DEFAULT;
--
-- Add field job_type to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "job_type" varchar(80) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "job_type" DROP DEFAULT;
--
-- Add field last_seen_at to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "last_seen_at" timestamp with time zone NULL;
--
-- Add field last_synced_at to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "last_synced_at" timestamp with time zone NULL;
--
-- Add field maximum_experience to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "maximum_experience" numeric(5, 1) NULL;
--
-- Add field minimum_experience to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "minimum_experience" numeric(5, 1) NULL;
--
-- Add field missing_sync_count to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "missing_sync_count" smallint DEFAULT 0 NOT NULL CHECK ("missing_sync_count" >= 0);
ALTER TABLE "edu_jobopening" ALTER COLUMN "missing_sync_count" DROP DEFAULT;
--
-- Add field preferred_skills to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "preferred_skills" jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "preferred_skills" DROP DEFAULT;
--
-- Add field qualification to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "qualification" varchar(255) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "qualification" DROP DEFAULT;
--
-- Add field remarks to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "remarks" text DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "remarks" DROP DEFAULT;
--
-- Add field required_skills to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "required_skills" jsonb DEFAULT '[]'::jsonb NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "required_skills" DROP DEFAULT;
--
-- Add field requisition_id to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "requisition_id" varchar(255) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "requisition_id" DROP DEFAULT;
--
-- Add field roles_and_responsibilities to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "roles_and_responsibilities" text DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "roles_and_responsibilities" DROP DEFAULT;
--
-- Add field salary_currency to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "salary_currency" varchar(8) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "salary_currency" DROP DEFAULT;
--
-- Add field salary_display to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "salary_display" varchar(120) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "salary_display" DROP DEFAULT;
--
-- Add field salary_maximum to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "salary_maximum" numeric(14, 2) NULL;
--
-- Add field salary_minimum to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "salary_minimum" numeric(14, 2) NULL;
--
-- Add field short_description to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "short_description" text DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "short_description" DROP DEFAULT;
--
-- Add field slug to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "slug" varchar(550) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "slug" DROP DEFAULT;
--
-- Add field source_type to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "source_type" varchar(40) DEFAULT 'manual' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "source_type" DROP DEFAULT;
--
-- Add field source_url to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "source_url" varchar(1000) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "source_url" DROP DEFAULT;
--
-- Add field state to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "state" varchar(120) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "state" DROP DEFAULT;
--
-- Add field work_mode to jobopening
--
ALTER TABLE "edu_jobopening" ADD COLUMN "work_mode" varchar(80) DEFAULT '' NOT NULL;
ALTER TABLE "edu_jobopening" ALTER COLUMN "work_mode" DROP DEFAULT;
--
-- Alter field is_active on company
--
CREATE INDEX "edu_company_is_active_32473429" ON "edu_company" ("is_active");
--
-- Alter field name on company
--
-- (no-op)
--
-- Alter field content_hash on jobopening
--
-- (no-op)
--
-- Alter field is_active on jobopening
--
CREATE INDEX "edu_jobopening_is_active_d44df9b2" ON "edu_jobopening" ("is_active");
--
-- Alter field location on jobopening
--
ALTER TABLE "edu_jobopening" ALTER COLUMN "location" TYPE varchar(500);
CREATE INDEX "edu_jobopening_location_7f17a58c" ON "edu_jobopening" ("location");
CREATE INDEX "edu_jobopening_location_7f17a58c_like" ON "edu_jobopening" ("location" varchar_pattern_ops);
--
-- Alter field posted_date on jobopening
--
CREATE INDEX "edu_jobopening_posted_date_14fc6d42" ON "edu_jobopening" ("posted_date");
--
-- Alter field title on jobopening
--
CREATE INDEX "edu_jobopening_title_0b8ac35a" ON "edu_jobopening" ("title");
CREATE INDEX "edu_jobopening_title_0b8ac35a_like" ON "edu_jobopening" ("title" varchar_pattern_ops);
--
-- Create index edu_company_is_acti_beefdb_idx on field(s) is_active, name of model company
--
CREATE INDEX "edu_company_is_acti_beefdb_idx" ON "edu_company" ("is_active", "name");
--
-- Create index edu_jobopen_company_9b0cf9_idx on field(s) company, is_active, -posted_date of model jobopening
--
CREATE INDEX "edu_jobopen_company_9b0cf9_idx" ON "edu_jobopening" ("company_id", "is_active", "posted_date" DESC);
--
-- Create index edu_jobopen_is_acti_f64646_idx on field(s) is_active, job_category of model jobopening
--
CREATE INDEX "edu_jobopen_is_acti_f64646_idx" ON "edu_jobopening" ("is_active", "job_category");
--
-- Create index edu_jobopen_is_acti_0940cb_idx on field(s) is_active, location of model jobopening
--
CREATE INDEX "edu_jobopen_is_acti_0940cb_idx" ON "edu_jobopening" ("is_active", "location");
--
-- Create index edu_jobopen_externa_1c4d1e_idx on field(s) external_job_id of model jobopening
--
CREATE INDEX "edu_jobopen_externa_1c4d1e_idx" ON "edu_jobopening" ("external_job_id");
--
-- Create constraint unique_company_external_job_id on model jobopening
--
CREATE UNIQUE INDEX "unique_company_external_job_id" ON "edu_jobopening" ("company_id", "external_job_id") WHERE NOT ("external_job_id" = '');
--
-- Add field company to jobsynclog
--
ALTER TABLE "edu_jobsynclog" ADD COLUMN "company_id" uuid NOT NULL CONSTRAINT "edu_jobsynclog_company_id_2190e353_fk_edu_company_id" REFERENCES "edu_company"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "edu_jobsynclog_company_id_2190e353_fk_edu_company_id" IMMEDIATE;
--
-- Add field job to savedjob
--
ALTER TABLE "edu_savedjob" ADD COLUMN "job_id" uuid NOT NULL CONSTRAINT "edu_savedjob_job_id_301df71f_fk_edu_jobopening_id" REFERENCES "edu_jobopening"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "edu_savedjob_job_id_301df71f_fk_edu_jobopening_id" IMMEDIATE;
--
-- Add field user to savedjob
--
ALTER TABLE "edu_savedjob" ADD COLUMN "user_id" uuid NOT NULL CONSTRAINT "edu_savedjob_user_id_1741a827_fk_edu_user_id" REFERENCES "edu_user"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "edu_savedjob_user_id_1741a827_fk_edu_user_id" IMMEDIATE;
--
-- Create index edu_jobsync_company_9244fd_idx on field(s) company, -started_at of model jobsynclog
--
CREATE INDEX "edu_jobsync_company_9244fd_idx" ON "edu_jobsynclog" ("company_id", "started_at" DESC);
--
-- Create constraint unique_user_saved_job on model savedjob
--
ALTER TABLE "edu_savedjob" ADD CONSTRAINT "unique_user_saved_job" UNIQUE ("user_id", "job_id");
CREATE INDEX "edu_jobsynclog_status_03a5a477" ON "edu_jobsynclog" ("status");
CREATE INDEX "edu_jobsynclog_status_03a5a477_like" ON "edu_jobsynclog" ("status" varchar_pattern_ops);
CREATE INDEX "edu_company_country_0723b919" ON "edu_company" ("country");
CREATE INDEX "edu_company_country_0723b919_like" ON "edu_company" ("country" varchar_pattern_ops);
CREATE INDEX "edu_company_industry_77ccdf9b" ON "edu_company" ("industry");
CREATE INDEX "edu_company_industry_77ccdf9b_like" ON "edu_company" ("industry" varchar_pattern_ops);
CREATE INDEX "edu_company_slug_709122ba_like" ON "edu_company" ("slug" varchar_pattern_ops);
CREATE INDEX "edu_jobopening_application_deadline_a46088f3" ON "edu_jobopening" ("application_deadline");
CREATE INDEX "edu_jobopening_city_449f202c" ON "edu_jobopening" ("city");
CREATE INDEX "edu_jobopening_city_449f202c_like" ON "edu_jobopening" ("city" varchar_pattern_ops);
CREATE INDEX "edu_jobopening_country_02ad17b9" ON "edu_jobopening" ("country");
CREATE INDEX "edu_jobopening_country_02ad17b9_like" ON "edu_jobopening" ("country" varchar_pattern_ops);
CREATE INDEX "edu_jobopening_job_category_c818c3a7" ON "edu_jobopening" ("job_category");
CREATE INDEX "edu_jobopening_job_category_c818c3a7_like" ON "edu_jobopening" ("job_category" varchar_pattern_ops);
CREATE INDEX "edu_jobopening_job_type_d3495b4f" ON "edu_jobopening" ("job_type");
CREATE INDEX "edu_jobopening_job_type_d3495b4f_like" ON "edu_jobopening" ("job_type" varchar_pattern_ops);
CREATE INDEX "edu_jobopening_minimum_experience_a0add6f8" ON "edu_jobopening" ("minimum_experience");
CREATE INDEX "edu_jobopening_qualification_ca8b70af" ON "edu_jobopening" ("qualification");
CREATE INDEX "edu_jobopening_qualification_ca8b70af_like" ON "edu_jobopening" ("qualification" varchar_pattern_ops);
CREATE INDEX "edu_jobopening_slug_42005a1b" ON "edu_jobopening" ("slug");
CREATE INDEX "edu_jobopening_slug_42005a1b_like" ON "edu_jobopening" ("slug" varchar_pattern_ops);
CREATE INDEX "edu_jobopening_state_99f3f677" ON "edu_jobopening" ("state");
CREATE INDEX "edu_jobopening_state_99f3f677_like" ON "edu_jobopening" ("state" varchar_pattern_ops);
CREATE INDEX "edu_jobopening_work_mode_6acfab89" ON "edu_jobopening" ("work_mode");
CREATE INDEX "edu_jobopening_work_mode_6acfab89_like" ON "edu_jobopening" ("work_mode" varchar_pattern_ops);
CREATE INDEX "edu_jobsynclog_company_id_2190e353" ON "edu_jobsynclog" ("company_id");
CREATE INDEX "edu_savedjob_job_id_301df71f" ON "edu_savedjob" ("job_id");
CREATE INDEX "edu_savedjob_user_id_1741a827" ON "edu_savedjob" ("user_id");
COMMIT;

-- ===== edu.0007_seed_verified_career_companies =====
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- ===== edu.0008_seed_additional_verified_workday_companies =====
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- ===== edu.0002_shortnote_shortnotepurchase_and_more =====
BEGIN;
--
-- Create model ShortNote
--
CREATE TABLE "edu_short_note" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "title" varchar(255) NOT NULL, "description" text NOT NULL, "price" numeric(8, 2) NOT NULL, "pdf_file" varchar(100) NULL, "word_file" varchar(100) NULL, "lesson_id" uuid NOT NULL);
--
-- Create model ShortNotePurchase
--
CREATE TABLE "edu_short_note_purchase" ("created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "id" uuid NOT NULL PRIMARY KEY, "purchased_at" timestamp with time zone NOT NULL, "payment_reference" varchar(255) NOT NULL, "amount_paid" numeric(8, 2) NOT NULL, "note_id" uuid NOT NULL, "user_id" uuid NOT NULL);
--
-- Create index edu_short_n_lesson__707981_idx on field(s) lesson of model shortnote
--
CREATE INDEX "edu_short_n_lesson__707981_idx" ON "edu_short_note" ("lesson_id");
--
-- Create index edu_short_n_user_id_893e8d_idx on field(s) user, note of model shortnotepurchase
--
CREATE INDEX "edu_short_n_user_id_893e8d_idx" ON "edu_short_note_purchase" ("user_id", "note_id");
--
-- Alter unique_together for shortnotepurchase (1 constraint(s))
--
ALTER TABLE "edu_short_note_purchase" ADD CONSTRAINT "edu_short_note_purchase_user_id_note_id_f1570fa4_uniq" UNIQUE ("user_id", "note_id");
ALTER TABLE "edu_short_note" ADD CONSTRAINT "edu_short_note_lesson_id_f1178d09_fk_edu_lesson_id" FOREIGN KEY ("lesson_id") REFERENCES "edu_lesson" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_short_note_created_at_b32f4971" ON "edu_short_note" ("created_at");
CREATE INDEX "edu_short_note_lesson_id_f1178d09" ON "edu_short_note" ("lesson_id");
ALTER TABLE "edu_short_note_purchase" ADD CONSTRAINT "edu_short_note_purchase_note_id_41630d70_fk_edu_short_note_id" FOREIGN KEY ("note_id") REFERENCES "edu_short_note" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "edu_short_note_purchase" ADD CONSTRAINT "edu_short_note_purchase_user_id_b969f90b_fk_edu_user_id" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "edu_short_note_purchase_created_at_1d50611d" ON "edu_short_note_purchase" ("created_at");
CREATE INDEX "edu_short_note_purchase_note_id_41630d70" ON "edu_short_note_purchase" ("note_id");
CREATE INDEX "edu_short_note_purchase_user_id_b969f90b" ON "edu_short_note_purchase" ("user_id");
COMMIT;

-- ===== edu.0005_merge_20260717_1712 =====

-- ===== edu.0009_merge_career_lounge_and_interview =====

-- ===== sessions.0001_initial =====
BEGIN;
--
-- Create model Session
--
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
COMMIT;

-- ===== token_blacklist.0001_initial =====
BEGIN;
--
-- Create model BlacklistedToken
--
CREATE TABLE "token_blacklist_blacklistedtoken" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "blacklisted_at" timestamp with time zone NOT NULL);
--
-- Create model OutstandingToken
--
CREATE TABLE "token_blacklist_outstandingtoken" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "jti" uuid NOT NULL UNIQUE, "token" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "expires_at" timestamp with time zone NOT NULL, "user_id" uuid NOT NULL);
--
-- Add field token to blacklistedtoken
--
ALTER TABLE "token_blacklist_blacklistedtoken" ADD COLUMN "token_id" integer NOT NULL UNIQUE CONSTRAINT "token_blacklist_blac_token_id_3cc7fe56_fk_token_bla" REFERENCES "token_blacklist_outstandingtoken"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "token_blacklist_blac_token_id_3cc7fe56_fk_token_bla" IMMEDIATE;
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_edu_user_" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "token_blacklist_outstandingtoken_user_id_83bc629a" ON "token_blacklist_outstandingtoken" ("user_id");
COMMIT;

-- ===== token_blacklist.0002_outstandingtoken_jti_hex =====
BEGIN;
--
-- Add field jti_hex to outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" ADD COLUMN "jti_hex" varchar(255) NULL;
COMMIT;

-- ===== token_blacklist.0003_auto_20171017_2007 =====
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- ===== token_blacklist.0004_auto_20171017_2013 =====
BEGIN;
--
-- Alter field jti_hex on outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "jti_hex" SET NOT NULL;
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq" UNIQUE ("jti_hex");
CREATE INDEX "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like" ON "token_blacklist_outstandingtoken" ("jti_hex" varchar_pattern_ops);
COMMIT;

-- ===== token_blacklist.0005_remove_outstandingtoken_jti =====
BEGIN;
--
-- Remove field jti from outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" DROP COLUMN "jti";
COMMIT;

-- ===== token_blacklist.0006_auto_20171017_2113 =====
BEGIN;
--
-- Rename field jti_hex on outstandingtoken to jti
--
ALTER TABLE "token_blacklist_outstandingtoken" RENAME COLUMN "jti_hex" TO "jti";
COMMIT;

-- ===== token_blacklist.0007_auto_20171017_2214 =====
BEGIN;
--
-- Alter field created_at on outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "created_at" DROP NOT NULL;
--
-- Alter field user on outstandingtoken
--
SET CONSTRAINTS "token_blacklist_outs_user_id_83bc629a_fk_edu_user_" IMMEDIATE; ALTER TABLE "token_blacklist_outstandingtoken" DROP CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_edu_user_";
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "user_id" DROP NOT NULL;
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_edu_user_" FOREIGN KEY ("user_id") REFERENCES "edu_user" ("id") DEFERRABLE INITIALLY DEFERRED;
COMMIT;

-- ===== token_blacklist.0008_migrate_to_bigautofield =====
BEGIN;
--
-- Alter field id on blacklistedtoken
--
ALTER TABLE "token_blacklist_blacklistedtoken" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "token_blacklist_blacklistedtoken_id_seq" AS bigint;
--
-- Alter field id on outstandingtoken
--
SET CONSTRAINTS "token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk" IMMEDIATE; ALTER TABLE "token_blacklist_blacklistedtoken" DROP CONSTRAINT "token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk";
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER SEQUENCE IF EXISTS "token_blacklist_outstandingtoken_id_seq" AS bigint;
ALTER TABLE "token_blacklist_blacklistedtoken" ALTER COLUMN "token_id" TYPE bigint USING "token_id"::bigint;
ALTER TABLE "token_blacklist_blacklistedtoken" ADD CONSTRAINT "token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk" FOREIGN KEY ("token_id") REFERENCES "token_blacklist_outstandingtoken" ("id") DEFERRABLE INITIALLY DEFERRED;
COMMIT;

-- ===== token_blacklist.0010_fix_migrate_to_bigautofield =====
BEGIN;
--
-- Alter field id on blacklistedtoken
--
-- (no-op)
--
-- Alter field id on outstandingtoken
--
-- (no-op)
COMMIT;

-- ===== token_blacklist.0011_linearizes_history =====

-- ===== token_blacklist.0012_alter_outstandingtoken_user =====
BEGIN;
--
-- Alter field user on outstandingtoken
--
-- (no-op)
COMMIT;

-- ===== token_blacklist.0013_alter_blacklistedtoken_options_and_more =====
BEGIN;
--
-- Change Meta options on blacklistedtoken
--
-- (no-op)
--
-- Change Meta options on outstandingtoken
--
-- (no-op)
COMMIT;

